version: '3'
services:
  api:
    build:
      context: ./backend-flask
    container_name: api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-api
    ports:
      - "5001:80"
  ui:
    build:
      context: ./my-app
    container_name: ui
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/app-ui
    ports:
      - "3000:3000"
